title: 第一个标题
author: arily 
email: 894231294@qq.com
description: 学习实践使用GitHub

# social links
twitter_username: arily
github_username:  arily

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
